name       : python-socketio
version    : 5.5.1
release    : 1
source     :
    - https://pypi.io/packages/source/p/python-socketio/python-socketio-5.5.1.tar.gz : ac8e64d59a15d1c31a4fe8434f4ff16d0f640c824ba517dce7ca99e95f0cd36a
license    : MIT
component  : programming.python
summary    : Socket.IO server and client for Python
description: |
    Python implementation of the Socket.IO_ realtime client and server.
rundeps    :
    - python-bidict
    - python-engineio
build      : |
    %python3_setup
install    : |
    %python3_install
