name       : python-socketio
version    : 5.5.2
release    : 2
source     :
    - https://pypi.io/packages/source/p/python-socketio/python-socketio-5.5.2.tar.gz : 6213f7dfbb87e554472d11151f96bae9059854aa88e4a1e0fa6e97cca1c3fcf4
license    : MIT
component  : programming.python
summary    : Socket.IO server and client for Python
description: |
    Python implementation of the Socket.IO_ realtime client and server.
rundeps    :
    - python-bidict
    - python-engineio
build      : |
    %python3_setup
install    : |
    %python3_install
